# build version
version: '{build}'

# branches to build
branches:
  # blacklist
  except:
    - gh-pages
    - travis
    - appveyor

# Do not build on tags
skip_tags: true

# enviroment settings
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  GCLOUD_PROJECT:
    secure: hEMdRRNQ5x4GHZcZGt6gsA==
  SECRET:
    secure: 8RQaiFWYQ8DoGCvFJhYYCSH063ZZQofpDxXjUZ8UZZsxVgzHQqjQz44pszw1KrjshkWD7qNHynxPOqlUDFGP9SAW08pzO1ckckNVyMVLDFMDj5WtWWXepZhTIvTbp+qJYU8ToZYzMTfOykov9uUfwS6Oy7e5RQW6SZ6S7ffuVkuRSCIkwL3YetsonB9Hl6ydKwXvyT5F+vd2xIsSkgvrlw9VVdMZl55d4Pd8nqDVDuM=

# install required tools (maven, secure-file, encrypted files)
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: echo %JAVA_HOME%
  - ps: $origin = git config --get remote.origin.url; git clone --quiet -b appveyor $origin appveyor
  - cmd: nuget install secure-file -ExcludeVersion
  - cmd: IF DEFINED SECRET (secure-file\tools\secure-file -decrypt appveyor\key.json.enc -secret %SECRET% -out appveyor\key.json)
  - cmd: IF DEFINED SECRET (SET GOOGLE_APPLICATION_CREDENTIALS=%APPVEYOR_BUILD_FOLDER%\appveyor\key.json)
  - cmd: ECHO %GOOGLE_APPLICATION_CREDENTIALS%

# build and install artifacts
build_script:
  - mvn clean install -DskipTests

# verify artifacts (no integration tests on PR)
test_script:
  - IF DEFINED APPVEYOR_PULL_REQUEST_NUMBER (mvn verify -DskipITs) ELSE (mvn verify)

# preserve dependencies between builds
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
