gapic_generator_version: 2.46.0
googleapis_commitish: 534e49c0ca0b9297f4ede6f119a0db054b35dd1e
libraries_bom_version: 26.47.0

# the libraries are ordered with respect to library name, which is
# java-{library.library_name} or java-{library.api-shortname} when
# library.library_name is not defined.
libraries:
- api_shortname: bigquerydatapolicy
  name_pretty: BigQuery DataPolicy API
  product_documentation: https://cloud.google.com/bigquery/docs/reference/datapolicy/
  api_description: ''
  GAPICs:
  - proto_path: google/cloud/bigquery/datapolicies/v1
  - proto_path: google/cloud/bigquery/datapolicies/v1beta1

- api_shortname: bigquerydatatransfer
  name_pretty: BigQuery Data Transfer Service
  product_documentation: https://cloud.google.com/bigquery/transfer/
  api_description: transfers data from partner SaaS applications to Google BigQuery
    on a scheduled, managed basis.
  release_level: stable
  issue_tracker: https://issuetracker.google.com/savedsearches/559654
  GAPICs:
  - proto_path: google/cloud/bigquery/datatransfer/v1