gapic_generator_version: 2.37.0
protobuf_version: '25.2'
googleapis_commitish: 20c357f6f5c7b995b617b15cab61999e6574bdab
owlbot_cli_image: sha256:623647ee79ac605858d09e60c1382a716c125fb776f69301b72de1cd35d49409
synthtool_commitish: 6612ab8f3afcd5e292aecd647f0fa68812c9f5b5
template_excludes:
- .github/*
- .kokoro/*
- samples/*
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
- SECURITY.md
- java.header
- license-checks.xml
- renovate.json
- .gitignore

# the libraries are ordered with respect to library name, which is
# java-{library.library_name} or java-{library.api-shortname} when
# library.library_name is not defined.
libraries:
- api_shortname: networkmanagement
  name_pretty: Network Management API
  product_documentation: https://cloud.google.com/network-intelligence-center/docs/connectivity-tests/reference/networkmanagement/rest/
  api_description: provides a collection of network performance monitoring and diagnostic
    capabilities.
  library_name: network-management
  release_level: stable
  GAPICs:
  - proto_path: google/cloud/networkmanagement/v1
  - proto_path: google/cloud/networkmanagement/v1beta1
