gapic_generator_version: 2.45.0
googleapis_commitish: a18d9b2c3563527b26c4b713469e795b92795271
libraries_bom_version: 26.47.0

# the libraries are ordered with respect to library name, which is
# java-{library.library_name} or java-{library.api-shortname} when
# library.library_name is not defined.
libraries:
- api_shortname: artifactregistry
  name_pretty: Artifact Registry
  product_documentation: https://cloud.google.com/artifact-registry
  api_description: provides a single place for your organization to manage container
    images and language packages (such as Maven and npm). It is fully integrated with
    Google Cloud's tooling and runtimes and comes with support for native artifact
    protocols. This makes it simple to integrate it with your CI/CD tooling to set
    up automated pipelines.
  library_name: artifact-registry
  release_level: stable
  codeowner_team: '@googleapis/aap-dpes'
  rest_documentation: https://cloud.google.com/artifact-registry/docs/reference/rest
  rpc_documentation: https://cloud.google.com/artifact-registry/docs/reference/rpc
  GAPICs:
  - proto_path: google/devtools/artifactregistry/v1
  - proto_path: google/devtools/artifactregistry/v1beta2

- api_shortname: cloudasset
  name_pretty: Cloud Asset Inventory
  product_documentation: https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/overview
  api_description: provides inventory services based on a time series database. This
    database keeps a five week history of Google Cloud asset metadata. The Cloud Asset
    Inventory export service allows you to export all asset metadata at a certain
    timestamp or export event change history during a timeframe.
  library_name: asset
  release_level: stable
  api_reference: https://cloud.google.com/resource-manager/docs/cloud-asset-inventory/overview
  issue_tracker: https://issuetracker.google.com/issues/new?component=187210&template=0
  GAPICs:
  - proto_path: google/cloud/asset/v1
  - proto_path: google/cloud/asset/v1p1beta1
  - proto_path: google/cloud/asset/v1p2beta1
  - proto_path: google/cloud/asset/v1p5beta1
  - proto_path: google/cloud/asset/v1p7beta1