# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

deep-remove-regex:
- "/java-bigqueryconnection/grpc-google-.*/src"
- "/java-bigqueryconnection/proto-google-.*/src"
- "/java-bigqueryconnection/google-.*/src"

deep-preserve-regex:
- "/java-bigqueryconnection/google-cloud-bigqueryconnection/src/test/java/com/google/cloud/bigqueryconnection/v.*/it/ITSystemTest.java"
- "/java-bigqueryconnection/proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/v1/ConnectionProto.java"
- "/java-bigqueryconnection/proto-google-cloud-bigqueryconnection-v1/src/main/java/com/google/cloud/bigquery/connection/ConnectionProto.java"
- "/java-bigqueryconnection/google-.*/src/main/resources/META-INF/native-image/.*"
- "/java-bigqueryconnection/google-.*/src/test/resources/META-INF/native-image/.*"

deep-copy-regex:
- source: "/google/cloud/bigquery/connection/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-bigqueryconnection/$1/proto-google-cloud-bigqueryconnection-$1/src"
- source: "/google/cloud/bigquery/connection/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-bigqueryconnection/$1/grpc-google-cloud-bigqueryconnection-$1/src"
- source: "/google/cloud/bigquery/connection/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-bigqueryconnection/$1/google-cloud-bigqueryconnection/src"

api-name: bigqueryconnection
