deep-remove-regex:
- "/java-edgenetwork/grpc-google-.*/src"
- "/java-edgenetwork/proto-google-.*/src"
- "/java-edgenetwork/google-.*/src"
- "/java-edgenetwork/samples/snippets/generated"

deep-preserve-regex:
- "/java-edgenetwork/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java"

deep-copy-regex:
- source: "/google/cloud/edgenetwork/(v.*)/.*-java/proto-google-.*/src"
  dest: "/owl-bot-staging/java-edgenetwork/$1/proto-google-cloud-edgenetwork-$1/src"
- source: "/google/cloud/edgenetwork/(v.*)/.*-java/grpc-google-.*/src"
  dest: "/owl-bot-staging/java-edgenetwork/$1/grpc-google-cloud-edgenetwork-$1/src"
- source: "/google/cloud/edgenetwork/(v.*)/.*-java/gapic-google-.*/src"
  dest: "/owl-bot-staging/java-edgenetwork/$1/google-cloud-edgenetwork/src"
- source: "/google/cloud/edgenetwork/(v.*)/.*-java/samples/snippets/generated"
  dest: "/owl-bot-staging/java-edgenetwork/$1/samples/snippets/generated"


api-name: edgenetwork
