# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api-name: file
deep-copy-regex:
  - dest: /owl-bot-staging/java-filestore/$1/proto-google-cloud-filestore-$1/src
    source: /google/cloud/filestore/(v.*)/.*-java/proto-google-.*/src
  - dest: /owl-bot-staging/java-filestore/$1/grpc-google-cloud-filestore-$1/src
    source: /google/cloud/filestore/(v.*)/.*-java/grpc-google-.*/src
  - dest: /owl-bot-staging/java-filestore/$1/google-cloud-filestore/src
    source: /google/cloud/filestore/(v.*)/.*-java/gapic-google-.*/src
  - dest: /owl-bot-staging/java-filestore/$1/samples/snippets/generated
    source: /google/cloud/filestore/(v.*)/.*-java/samples/snippets/generated
deep-preserve-regex:
  - /java-filestore/google-.*/src/test/java/com/google/cloud/.*/v.*/it/IT.*Test.java
  - /java-filestore/google-.*/src/main/resources/META-INF/native-image/*
  - /java-filestore/google-.*/src/test/resources/META-INF/native-image/*
deep-remove-regex:
  - /java-filestore/samples/snippets/generated
  - /java-filestore/grpc-google-.*/src
  - /java-filestore/proto-google-.*/src
  - /java-filestore/google-.*/src
