name: CI
on:
  schedule:
    - cron: '0 1 * * *' # nightly at 1 am
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Monorepo
        run: ./monorepo.sh
      - name: Archive code coverage
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: monorepo/google-cloud-java/CoverageAggregator/target/site/jacoco-aggregate
