name: CI
on:
  schedule:
    - cron: '0 1 * * *' # nightly at 1 am UTC
  push:
    branches: [ monorepo_main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Monorepo
        run: ./bootstrap.sh
        env:
          USERNAME: ${{ github.actor }}
