name: CI
on:
  schedule:
    - cron: '0 1 * * *' # nightly at 1 am UTC
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Monorepo
        run: ./bootstrap.sh
        env:
          USERNAME: ${{ github.actor }}
      - name: Compile
        working-directory: monorepo/google-cloud-java
        run: mvn compile -T C1 -B
      - name: Unit Tests
        working-directory: monorepo/google-cloud-java
        run: mvn test -T C1 -B
      - name: Aggregate coverage
        working-directory: monorepo/google-cloud-java
        run: mvn jacoco:report-aggregate -T C1 -B
      - name: Create code coverage archive
        working-directory: monorepo/google-cloud-java/CoverageAggregator/target/site/jacoco-aggregate
        run: zip ../../../../../coverage.zip ./* -r
      - name: Upload code coverage archive
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: monorepo/coverage.zip
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: monorepo/google-cloud-java/CoverageAggregator/target/site/jacoco-aggregate
      - name: Push monorepo to branch
        run: |
          cd monorepo/google-cloud-java
          git remote add monorepo https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f monorepo main:monorepo