name: Pull Request Test

on:
  workflow_dispatch:
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - run: |
        npm i code-suggester -g
    - run: |
        code-suggester --version
    - uses: actions/checkout@v3
      with:
        repository: 'googleapis/google-cloud-java'
    - run: |
        echo "This is a new file from pull request." >> NEW_FILE.md
        git config user.email "google-cloud-java-automation[bot]@users.noreply.github.com"
        git config user.name "google-cloud-java-automation"
        git add --all
        git commit -m 'build: adding a new file'
    - run: |
        code-suggester pr --upstream-owner=googleapis --upstream-repo=google-cloud-java \
            --title='suztomo code-suggester test' \
            --description='This is test by suztomo' \
            --message='This is commit message via code-suggester' \
            --git-dir=.
      env:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"

