name: Generate new GAPIC client library
on:
  workflow_dispatch:
      inputs:
        api_shortname:
          required: true
          type: string
          description: Name for the new directory name and (default) artifact name
        name_pretty:
          required: true
          type: string
          description: The human-friendly name that appears in README.md
        proto_path:
          required: true
          type: string
          description: |
            Path to proto file from the root of the googleapis repository to the
            directory that contains the proto files (without the version).
            For example, to generate the library for 'google/maps/routing/v2',
            then you specify this value as 'google/maps/routing'
        product_docs:
          required: true
          type: string
          description: Documentation URL that appears in README.md
        rest_docs:
          required: false
          type: string
          description: |
            If it exists, link to the REST Documentation for a service
        rpc_docs:
          required: false
          type: string
          description: |
            If it exists, link to the RPC Documentation for a service
        api_description:
          required: true
          description: Description that appears in README.md
        release_level:
          required: false
          type: choice
          default: preview
          options:
            - stable
            - preview
          description: |
            A label that appears in repo-metadata.json.
            The first library generation is always 'preview'.
        transport:
          required: false
          type: choice
          default: grpc
          options:
            - grpc
            - http
            - both
          description: A label that appears in repo-metadata.json
        language:
          required: false
          type: string
          default: java
        distribution_name:
          required: false
          type: string
          description: |
            Maven coordinates of the generated library. By default it's 
            "com.google.cloud:google-cloud-<api_shortname>"
        api_id:
          required: false
          type: string
          description: |
            The value of the apiid parameter used in README.md It has link to
            "https://console.cloud.google.com/flows/enableapi?apiid=<api_id>"
        requires_billling:
          required: false
          type: boolean
          default: true
          description: |
            Based on this value, README.md explains whether billing setup is
            "needed or not."
        destination_name:
          required: false
          type: string
          default: null
          description: |
            The directory name of the new library. By default it's
            "java-<api_shortname>"
        cloud_api:
          required: false
          type: boolean
          default: true
          description: |
            If true, the artifact ID of the library is 'google-cloud-'
            otherwise 'google-'
        group_id:
          required: false
          type: string
          default: com.google.cloud
          description: |
            The group ID of the artifact when distribution name is not set
        owlbot_image:
          required: false
          type: string
          default: gcr.io/cloud-devrel-public-resources/owlbot-java
          description: The owlbot container image used in OwlBot.yaml
        library_type:
          required: false
          type: string
          default: GAPIC_AUTO
          description: |
            A label that appear in repo-metadata.json to tell how the library is
            maintained or generated

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Get current week within the year
        id: date
        run: echo "::set-output name=week_of_year::$(date +'%W' --utc)"
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - run: java -version
      - run: echo 'a message'
      - name: Generate
        run: |
          python generation/new_client/new-client.py generate \
              --api_shortname=${API_SHORT_NAME} \
              --proto-path=${PROTO_PATH} \
              --name-pretty="${API_PRETTY_NAME}" \
              --product-docs="https://github.com/googleapis/google-cloud-java/tree/main/java-${API_SHORT_NAME}" \
              --api-description="${API_PRETTY_NAME} Client lets you use ${API_PRETTY_NAME} API." \
              --googleapis-gen-url=https://yoshi-approver:${{ secrets.YOSHI_APPROVER_PRIVATE_TOKEN }}@github.com/googleapis/googleapis-gen.git

