on:
  pull_request:
jobs:
  library-generation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run generate_libraries.sh
      shell: bash
      run: |
        cd library_generation
        bash generate_libraries.sh
        echo "Code generation finished"
