name: Hermetic library generation upon generation config change through pull requests
on:
  pull_request:
    paths:
    - "generation_config.yaml"

jobs:
  library_generation:
    runs-on: ubuntu-latest
    env:
      library_generation_image_tag: 2.39.0
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate changed libraries
      shell: bash
      run: |
        set -x
        bash generation/hermetic_library_generation.sh \
          --target_branch ${{ github.base_ref }} \
          --current_branch ${{ github.head_ref }} \
          --image_tag "${library_generation_image_tag}"
      env:
        GH_TOKEN: ${{ secrets.CLOUD_JAVA_BOT_TOKEN }}
