name: CI
on:
  schedule:
    - cron: '0 1 * * *' # nightly at 1 am UTC
  push:
    branches: [ monorepo_script ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Monorepo
        run: ./bootstrap.sh
        env:
          USERNAME: ${{ github.actor }}
      - name: Compile
        working-directory: monorepo/google-cloud-java
        run: mvn compile -T C1 -B
      - name: Unit Tests
        working-directory: monorepo/google-cloud-java
        run: mvn test -T C1 -B
      - name: Push monorepo to branch
        run: |
          cd monorepo/google-cloud-java
          git remote add monorepo https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f monorepo main:monorepo_script_output