name: New Client
on:
  schedule:
    - cron: '0 2 * * *' # nightly at 2 am UTC
  push:
    branches: [ main ]
    paths:
      - generation/**
  pull_request:
    branches: [ main ]
    paths:
      - generation/**

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r generation/new_client/requirements.txt
      - name: Remove other libraries
        run: rm -rf java-*
      - name: Generate
        run: |
          python generation/new_client/new-client.py generate \
              --api_shortname=apikeys \
              --proto-path=google/api/apikeys \
              --name-pretty="API Keys API" \
              --product-docs="https://cloud.google.com/api-keys/" \
              --api-description="API Keys lets you create and manage your API keys for your projects."
              --googleapis-gen-url=https://${{ secrets.YOSHI_CODE_BOT_TOKEN }}@github.com/googleapis/googleapis-gen.git
      - name: Push to branch
        run: |
          git add --all
          git commit -m 'feat: added apikeys and removed others'
          git push -f origin main:newclient_output_${{ github.event_name }}
      - name: Test
        run: mvn install