# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  workflow_dispatch:
  schedule:
  # every morning
  - cron: '0 1 * * *'
name: readme
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: python3 -m pip install requests
    - run: python3 generate-readme.py
    - run: |
        git config user.email "suztomo@users.noreply.github.com"
        git config user.name "Tomo Suzuki"        
        git checkout -b update-readme
        git add README.md
        git commit -m 'docs: regenerate readme'
        git push -f -u origin "update-readme"
        gh pr create --title="regenerate readme" \
            --body "Auto-generated pull request from readme.yaml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
