on:
  pull_request:
jobs:
  run-protoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run run_protoc.sh
      shell: bash
      run: |
        cd java-monitoring
        sh -x run_protoc.sh
        echo "Code generation finished"
    - name: Compare with googleapis-gen
      shell: bash
      run: |
        cd library_generation
        sh -x compare.sh
        echo "Comparison finished"
