name: GH comand test
on:
  workflow_dispatch:
  pull_request:
jobs:
  create-pull-request:
    name: Create pull request for changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'googleapis/google-cloud-java'
    - name: Prepare workspace
      run: |
        mkdir -p "${WORKSPACE}"
        git clone --quiet --depth 1 --branch monorepo_script_output \
            https://github.com/googleapis/google-cloud-java \
            "${WORKSPACE}/google-cloud-java"
        cd "${WORKSPACE}/google-cloud-java"
      env:
        WORKSPACE: /tmp/googleapis-sync
        GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    - name: Commit some changes to monorepo_script_output-googleapis-sync
      run: |
        echo "Hello, monorepo!" >> README.md
        git config user.email "yoshi-code-bot[bot]@users.noreply.github.com"
        git config user.name "yoshi-code-bot"
        
        git checkout -b monorepo_googleapis_change
        
        git add --all
        git commit -m 'chore: adding a line to README.md before code-suggester'
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Create some changes for code-suggester
      run: |
        date > googleapis-sync.timestamp.txt
        git add --all
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Check any diff
      run: |
        git status
        git diff
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Push changes to remote
      run: |
        git remote add origin_with_auth https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
        git push -f --set-upstream origin_with_auth monorepo_googleapis_change
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Create pull request
      run: |
        gh pr create --title='chore: googleapis change propagation via hermetic build' \
            --body='googleapis change propagation via hermetic build' \
            --base=monorepo_script_output \
            --head=monorepo_googleapis_change
      working-directory: /tmp/googleapis-sync/google-cloud-java
      env:
        GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}

