name: Code Suggester TEst
on:
  workflow_dispatch:
  pull_request:
jobs:
  create-pull-request:
    name: Create pull request for changes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'googleapis/google-cloud-java'
    - name: Prepare workspace
      run: |
        mkdir -p "${WORKSPACE}"
        git clone --quiet --depth 1 --branch monorepo_script_output \
            https://github.com/googleapis/google-cloud-java \
            "${WORKSPACE}/google-cloud-java"
        cd "${WORKSPACE}/google-cloud-java"
      env:
        WORKSPACE: /tmp/googleapis-sync
        GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
    - name: Commit some changes to monorepo_script_output-googleapis-sync
      run: |
        echo "Hello, monorepo!" >> README.md
        git config user.email "yoshi-code-bot[bot]@users.noreply.github.com"
        git config user.name "yoshi-code-bot"
        git add --all
        git commit -m 'chore: adding a line to README.md before code-suggester'
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Create some changes for code-suggester
      run: |
        date > googleapis-sync.timestamp.txt
        git add --all
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - name: Check any diff
      run: |
        git status
        git diff
      working-directory: /tmp/googleapis-sync/google-cloud-java
    - uses: googleapis/code-suggester@v3
      env:
        ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      with:
        command: pr
        upstream_owner: googleapis
        upstream_repo: google-cloud-java
        description: 'googleapis change propagation via hermetic build'
        title: 'chore: googleapis change propagation via hermetic build'
        message: 'chore: googleapis change propagation mark'
        # Upon main branch cutover, change it to 'googleapis-sync'
        branch: monorepo_script_output
        # Upon main branch cutover, change it to main
        primary: monorepo_script_output
        force: true
        # This needs to match the 'google-cloud-java' directory in the
        #  WORKSPACE in the previous step
        git_dir: /tmp/googleapis-sync/google-cloud-java
