'on':
  push:
    branches:
      - 1.13.x
  pull_request: null
name: versions check
jobs:
  unmanaged-versions-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./generation/check_non_release_please_versions.sh
  existing-versions-check:
    runs-on: ubuntu-latest
    if: >
      github.repository_owner == 'googleapis' && github.head_ref ==
      'release-please--branches--main' &&

      (github.event_name != 'pull_request' ||
      !contains(github.event.pull_request.labels.*.name, 'autorelease:
      snapshot'))
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install libxml2-utils
      - uses: actions/checkout@v3
      - run: ./generation/check_existing_release_versions.sh
